version: "3"
services:
    webserver:
        image: nginx:alpine
        container_name: project-build-webserver
        volumes:
            - ../../application:/application
            - ../../Docker/nginx/nginx-php.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8055:80"

    php-fpm:
        build: ../../Docker/php-fpm
        container_name: my-project-php-build-fpm
        working_dir: /application
        volumes:
            - ../../application:/application
            - ../../Docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini