version: "3"
services:
    webserver:
        image: nginx:alpine
        container_name: project-webserver-mysql-redis
        working_dir: /application
        volumes:
            - ../../application:/application
            - ../../Docker/nginx/nginx-php-mysql-redis.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "8055:80"

    php-fpm:
        build: ../../Docker/php-fpm-mysql-redis-memcached
        container_name: my-project-php-fpm-mysql-redis
        working_dir: /application
        volumes:
          - ../../application:/application
          - ../../Docker/php-fpm-mysql-redis-memcached/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        links:
          - mysql

    mysql:
        image: mysql:5.7
        container_name: my-project-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root123
            - MYSQL_DATABASE=example_database
            - MYSQL_USER=example_user
            - MYSQL_PASSWORD=secret
            - MYSQL_ALLOW_EMPTY_PASSWORD=true

    redis:
        image: redis:alpine
        container_name: my-project-redis

    memcached:
        image: memcached:alpine
        container_name: my-project-memcached