version: "3"
services:
    webserver:
        image: nginx:alpine
        container_name: project-webserver
        working_dir: /application
        volumes:
            - ../../application:/application
            - ../../Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
          - "8055:80"